sudo: false

language: go

dist: xenial

go:
  - 1.14.x

env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/librato
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}

cache:
  directories:
  - $GOPATH/pkg/dep/sources

before_install:
  - "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"

install:
  - cd $SNAP_PLUGIN_SOURCE
  - make deps

script: make check 2>&1

jobs:
  include:
  - stage: lint
    env:
      - TEST_TYPE=lint
    script:
      - make check 2>&1
      - go install ./vendor/honnef.co/go/tools/cmd/staticcheck
      - staticcheck ./...
  - stage: build
    script:
      - wget https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get update
      - sudo apt-get install gcc-multilib
      - sudo apt-get install gcc-mingw-w64
      - sudo apt-get install -y apt-transport-https
      - sudo apt-get install -y dotnet-sdk-3.1
      - sudo apt-get install -y dotnet-runtime-3.1
      - make build 2>&1
  - stage: test
    env: TEST_TYPE=small
  - stage: test
    env: TEST_TYPE=medium

stages:
- lint
- build
- test
