sudo: false

language: go

go:
  - 1.11.x

env:
  global:
  - ORG_PATH=/home/travis/gopath/src/github.com/librato
  - SNAP_PLUGIN_SOURCE=/home/travis/gopath/src/github.com/${TRAVIS_REPO_SLUG}

cache:
  directories:
  - $GOPATH/pkg/dep/sources

before_install:
  - "[[ -d $SNAP_PLUGIN_SOURCE ]] || mkdir -p $ORG_PATH && ln -s $TRAVIS_BUILD_DIR $SNAP_PLUGIN_SOURCE"

install:
  - cd $SNAP_PLUGIN_SOURCE
  - make deps

script: make check 2>&1

jobs:
  include:
  - stage: lint
    env:
      - TEST_TYPE=lint
    script:
      - make check 2>&1
      - go install ./vendor/honnef.co/go/tools/cmd/staticcheck
      - staticcheck ./...
  - stage: test
    env: TEST_TYPE=small
  - stage: test
    env: TEST_TYPE=medium

stages:
- lint
- test
