# Needed for Travis lint stage
required = [
  "honnef.co/go/tools/cmd/staticcheck"
]

[[override]]
  name="honnef.co/go/tools"
  revision="d36bf90409063c0fe4fecdc07cc71e25b59a4050"
  #branch = "master"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "=v1.5.2"

[prune]
  go-tests = true
  unused-packages = true

