# Needed for Travis lint stage
required = [
  "honnef.co/go/tools/cmd/staticcheck"
]

[[override]]
  name="honnef.co/go/tools"
  revision="d36bf90409063c0fe4fecdc07cc71e25b59a4050"

# Actual code dependencies
[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.1.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.19.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.4.0"

[[override]]
  name = "github.com/cpuguy83/go-md2man"
  version = "=v1.0.9"

[prune]
  go-tests = true
  unused-packages = true
