# Needed for Travis lint stage
required = [
  "honnef.co/go/tools/cmd/staticcheck"
]

[[override]]
  name = "github.com/russross/blackfriday"
  version = "=v1.5.2"

[prune]
  go-tests = true
  unused-packages = true

