# Needed for Travis lint stage
required = [
  "honnef.co/go/tools/cmd/staticcheck"
]

[[override]]
  name="honnef.co/go/tools"
  revision="d36bf90409063c0fe4fecdc07cc71e25b59a4050"

[[override]]
  name = "github.com/cpuguy83/go-md2man"
  version = "=v1.0.9"

[prune]
  go-tests = true
  unused-packages = true

